package conddb.data;

// Generated Aug 25, 2014 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GlobalTagMapId generated by hbm2java
 */
@Embeddable
public class GlobalTagMapId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2725375515465300712L;
	private String globalTagName;
	private Long tagId;

	public GlobalTagMapId() {
	}

	public GlobalTagMapId(String globalTagName, Long tagId) {
		this.globalTagName = globalTagName;
		this.tagId = tagId;
	}
	
	@Column(name="GLOBAL_TAG_NAME")
	public String getGlobalTagName() {
		return globalTagName;
	}

	public void setGlobalTagName(String globalTagName) {
		this.globalTagName = globalTagName;
	}

	@Column(name="TAG_ID")
	public Long getTagId() {
		return tagId;
	}

	public void setTagName(Long tagId) {
		this.tagId = tagId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GlobalTagMapId))
			return false;
		GlobalTagMapId castOther = (GlobalTagMapId) other;

		return (((this.getGlobalTagName() == castOther.getGlobalTagName()) &&
				(this.getTagId() == castOther.getTagId())) || 
				(this.getGlobalTagName() != null && castOther.getGlobalTagName() != null && this.getGlobalTagName().equals(castOther.getGlobalTagName())
				&& (this.getTagId() != null && castOther.getTagId() != null && this.getTagId().equals(castOther.getTagId()))));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getGlobalTagName() == null ? 0 : this.getGlobalTagName().hashCode());
		result = 37 * result
				+ (getTagId() == null ? 0 : this.getTagId().hashCode());
		
		return result;
	}
	
}
