package conddb.data;

// Generated Aug 25, 2014 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.time.Instant;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import conddb.utils.json.serializers.TimestampDeserializer;

/**
 * Iov generated by hbm2java
 */
@Entity
@Table(name = "PHCOND_IOV", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"SINCE", "INSERTION_TIME", "TAG_ID" }) })
//@//JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, property = "@id")
@JsonIdentityInfo(generator = ObjectIdGenerators.PropertyGenerator.class, property = "id")
public class Iov implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7499748521778474013L;

	private Long id;
	private BigDecimal since;
	private String sinceString;
	private Timestamp insertionTime;

	private Payload payload;
	private Tag tag;

	public Iov() {
	}

	public Iov(BigDecimal since, String sincestr, Timestamp insertiontime,
			Payload payload, Tag tag) {
		this.since = since;
		this.sinceString = sincestr;
		this.insertionTime = insertiontime;
		this.payload = payload;
		this.tag = tag;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "IOV_ID", nullable=false, precision = 22, scale = 0)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "SINCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSince() {
		return this.since;
	}

	public void setSince(BigDecimal since) {
		this.since = since;
	}

	@Column(name = "SINCE_STRING", nullable = false, length = 255)
	public String getSinceString() {
		return sinceString;
	}

	public void setSinceString(String sinceString) {
		this.sinceString = sinceString;
	}

//	@JsonSerialize(using = DateSerializer.class)
//	@Temporal(TemporalType.TIMESTAMP)
	@JsonDeserialize(using = TimestampDeserializer.class)
	@Column(name = "INSERTION_TIME", nullable = false)
	public Timestamp getInsertionTime() {
		return this.insertionTime;
	}

	public void setInsertionTime(Timestamp insertionTime) {
		this.insertionTime = insertionTime;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "PAYLOAD_HASH", nullable = false, updatable = false)
	//@//JsonSerialize(using = PayloadSerializer.class)
	//@//JsonIgnore
	//@JsonManagedReference
	public Payload getPayload() {
		return this.payload;
	}

	public void setPayload(Payload payload) {
		this.payload = payload;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "TAG_ID", nullable = false, updatable = false)
//	@JsonIgnore
	//@JsonBackReference
	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	@PrePersist
    public void prePersist() {
		Instant now = Instant.now();
        Timestamp nowt = Timestamp.from(now);
        this.insertionTime = nowt;
    }

}
