package conddb.data;

// Generated Aug 25, 2014 4:52:00 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.ser.std.DateSerializer;

/**
 * IovId generated by hbm2java
 */
@Embeddable
public class IovOldId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8973931257189987321L;
	private String tagName;
	private BigDecimal since;
	private Date insertionTime;

	public IovOldId() {
	}

	public IovOldId(String tagName, BigDecimal since, Date insertionTime) {
		this.tagName = tagName;
		this.since = since;
		this.insertionTime = insertionTime;
	}

	@Column(name = "TAG_NAME", nullable = false, length = 100)
	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	@Column(name = "SINCE", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSince() {
		return this.since;
	}

	public void setSince(BigDecimal since) {
		this.since = since;
	}

	@JsonSerialize(using=DateSerializer.class)
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERTION_TIME", nullable = false)
	public Date getInsertionTime() {
		return this.insertionTime;
	}

	public void setInsertionTime(Date insertionTime) {
		this.insertionTime = insertionTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof IovOldId))
			return false;
		IovOldId castOther = (IovOldId) other;

		return ((this.getTagName() == castOther.getTagName()) || (this
				.getTagName() != null && castOther.getTagName() != null && this
				.getTagName().equals(castOther.getTagName())))
				&& ((this.getSince() == castOther.getSince()) || (this
						.getSince() != null && castOther.getSince() != null && this
						.getSince().equals(castOther.getSince())))
				&& ((this.getInsertionTime() == castOther.getInsertionTime()) || (this
						.getInsertionTime() != null
						&& castOther.getInsertionTime() != null && this
						.getInsertionTime()
						.equals(castOther.getInsertionTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTagName() == null ? 0 : this.getTagName().hashCode());
		result = 37 * result
				+ (getSince() == null ? 0 : this.getSince().hashCode());
		result = 37
				* result
				+ (getInsertionTime() == null ? 0 : this.getInsertionTime()
						.hashCode());
		return result;
	}

}
