package conddb.data;

// Generated Aug 25, 2014 4:52:00 PM by Hibernate Tools 3.4.0.CR1

//import conddb.data.deserialiser.*;
//import conddb.mappers.deserializers.PayloadDeserializer;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;

import conddb.utils.hash.HashGenerator;

/**
 * Payload generated by hbm2java
 */
@Entity
@Table(name = "PAYLOAD")
@JsonIdentityInfo(generator=ObjectIdGenerators.PropertyGenerator.class, property="hash")
//@JsonDeserialize(using=PayloadDeserializer.class)
//@JsonSerialize(using = PayloadSerializer.class)
public class Payload implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6319755970273574624L;
	private String hash;
	private String version;
	private String objectType;
	private String data;
	private String streamerInfo;
	private Date insertionTime;
	private Set<Iov> iovs = new HashSet<Iov>(0);

	private String dataBuf;
	private String streamerInfoBuf;
	
	public Payload() {
		//default constructor creates an empty payload with only 
		// a String saying EMPTY
		this.objectType="DEFAULT";
		this.data = "EMPTY";
		this.streamerInfo = "String";
		this.insertionTime = new Date();
		this.version = "0.0";
		this.hash = HashGenerator.md5Spring("EMPTY_LOB");
	}

	public Payload(String hash, String objectType, String data,
			String streamerInfo, Date insertionTime, String version) {
		this.hash = hash;
		this.objectType = objectType;
		this.data = data;
		this.streamerInfo = streamerInfo;
		this.insertionTime = insertionTime;
		this.version = version;
	}

	public Payload(String hash, String objectType, String data,
			String streamerInfo, Date insertionTime,  String version, Set<Iov> iovs) {
		this.hash = hash;
		this.objectType = objectType;
		this.data = data;
		this.streamerInfo = streamerInfo;
		this.insertionTime = insertionTime;
		this.version = version;
		this.iovs = iovs;
	}

	
	/**
	 * @param hash
	 * @param version
	 * @param objectType
	 * @param insertionTime
	 * @param dataBuf
	 * @param streamerInfoBuf
	 */
	public Payload(String hash, String version, String objectType,
			Date insertionTime, String dataBuf, String streamerInfoBuf) {
		super();
		this.hash = hash;
		this.version = version;
		this.objectType = objectType;
		this.insertionTime = insertionTime;
		this.dataBuf = dataBuf;
		this.streamerInfoBuf = streamerInfoBuf;
	}

	@Id
	@Column(name = "HASH", unique = true, nullable = false, length = 40)
	public String getHash() {
		return this.hash;
	}

	public void setHash(String hash) {
		this.hash = hash;
	}

	@Column(name = "VERSION", nullable = false, length = 20)
	public String getVersion() {
		return this.version;
	}

	public void setVersion(String version) {
		this.version = version;
	}

	@Column(name = "OBJECT_TYPE", nullable = false, length = 100)
	public String getObjectType() {
		return this.objectType;
	}

	public void setObjectType(String objectType) {
		this.objectType = objectType;
	}

	@Column(name = "DATA", nullable = false)
	@Lob
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	@Column(name = "STREAMER_INFO", nullable = false)
	@Lob
	public String getStreamerInfo() {
		return this.streamerInfo;
	}

	public void setStreamerInfo(String streamerInfo) {
		this.streamerInfo = streamerInfo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "INSERTION_TIME", nullable = false)
	public Date getInsertionTime() {
		return this.insertionTime;
	}

	public void setInsertionTime(Date insertionTime) {
		this.insertionTime = insertionTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "payload")
	public Set<Iov> getIovs() {
		return this.iovs;
	}

	public void setIovs(Set<Iov> iovs) {
		this.iovs = iovs;
	}

	@Transient
	public String getDataBuf() {
		return dataBuf;
	}

	public void setDataBuf(String dataBuf) {
		this.dataBuf = dataBuf;
	}

	@Transient
	public String getStreamerInfoBuf() {
		return streamerInfoBuf;
	}

	public void setStreamerInfoBuf(String streamerInfoBuf) {
		this.streamerInfoBuf = streamerInfoBuf;
	}
}
